version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    volumes:
      - "./app:/app"
    image: andriichernov/devops-for-programmers-project-lvl1
    depends_on: [db]

  db:
    image: postgres:latest
    restart: always
    env_file: 
    - ./.env
