version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    volumes:
      - "./app:/app"
    image: andriichernov/devops-for-programmers-project-lvl1
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    depends_on: [db]

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
