version: "3"

services:

  app:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - "./app:/app"

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
