version: "3"

services:

  app:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - "./app:/app"
    
  caddy:
    image: caddy:latest
    ports:
      - 8081:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
