name: Docker Actions

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build --no-cache app
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app
      - name: Login to DockerHub Registry
        if: always()
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image
        if: always()
        run: docker-compose -f docker-compose.yml push app
